config/routes.rb
Rails.application.routes.draw do
  resources :empresas

  resources :tipo_pagamentos

  devise_for :users
  
  resources :redespachos
  resources :dashboard
  
  root 'dashboard#index'
  

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  has_one :redespacho
end

app/models/redespacho.rb
class Redespacho < ActiveRecord::Base
  belongs_to :empresa
end

app/models/tipo_pagamento.rb
class TipoPagamento < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]
  before_action :set_listagem

  respond_to :html

  def index
    respond_with(@empresas)
  end

  def show
    respond_with(@empresa)
  end

  def new
    @empresa = Empresa.new
    respond_with(@empresa)
  end

  def edit
  end

  def create
    @empresa = Empresa.new(empresa_params)
    flash[:notice] = 'Empresa foi cadastrada.' if @empresa.save
    respond_with(@empresa)
  end

  def update
    flash[:notice] = 'Empresa atualizada com sucesso.' if @empresa.update(empresa_params)
    respond_with(@empresa)
  end

  def destroy
    @empresa.destroy
    respond_with(@empresa)
  end

  private
  
    def set_listagem
      @empresas = initialize_grid(Empresa.order(created_at: :desc), per_page: 20)
    end
  
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    def empresa_params
      params.require(:empresa).permit(:nome, :razao_social, :cnpj, :email, :telefone, :responsavel, :cidade, :estado, :observacao)
    end
end

app/controllers/redespachos_controller.rb
class RedespachosController < ApplicationController
  before_action :carrega_lista
  
  def index
    #@registros = Redespacho.all
    @redespacho = Redespacho.new 
  end
  
  def show
    
  end
  
  def new
    @redespacho = Redespacho.new
  end
  
  def edit
    @redespacho = Redespacho.find(params[:id])
    respond_to do |format|
      format.html {render 'edit'}
    end
    #flash[:notice] = 'Não esqueça de salvar as alteçoes após a edição.'
  end
  
  def create
    begin
      @redespacho = Redespacho.new(redespacho_params)
      
      respond_to do |format|
        if @redespacho.save
          format.html {redirect_to redespachos_path, notice: 'Redespacho salvo com sucesso!'}
        else
          format.html {redirect_to redespachos_path, notice: 'Nem todos os campos foram preenchidos!'}
        end
      end
    rescue
      respond_to do |format|
        format.html {redirect_to redespachos_path, notice: 'Um erro aconteceu :( '}
      end
    end
  end
  
  def update
    @redespacho = Redespacho.find(params[:id])
    if(@redespacho.update(redespacho_params))
      respond_to do |format|
        format.html {redirect_to redespachos_path, notice: 'Redespacho atualizado com sucesso!'}
      end
    else
      respond_to do |format|
        render :action => 'edit'
      end    
    end
    
  end
  
  private
  
  def carrega_lista
    @registros = initialize_grid(Redespacho.order(created_at: :desc), per_page: 30)
  end
  
  def redespacho_params
    params.require(:redespacho).permit(:remetente,:destinatario, :destinatario_cidade, :valor_redespacho,
    :valor_comissao, :valor_liquido, :valor_frete, :volume, :peso, :nf_valor, :nf_numero, :forma_pagamento,
    :data_envio, :data_entrega, :recebido_por, :jadlog_lista_numero, :jadlog_conhecimento_numero, :empresa_id)
  end
end

app/controllers/tipo_pagamentos_controller.rb
class TipoPagamentosController < ApplicationController
  before_action :set_tipo_pagamento, only: [:show, :edit, :update, :destroy]
  before_action :set_listagem
  
  respond_to :html

  def index
    respond_with(@tipo_pagamentos)
  end

  def show
    respond_with(@tipo_pagamento)
  end

  def new
    @tipo_pagamento = TipoPagamento.new
    respond_with(@tipo_pagamento)
  end

  def edit
  end

  def create
    @tipo_pagamento = TipoPagamento.new(tipo_pagamento_params)
    #flash[:notice] = 'TipoPagamento was successfully created.' 
    if @tipo_pagamento.save
      respond_to do |format|
        format.html {redirect_to tipo_pagamentos_path, notice: 'Tipo de pagamento cadastrado com sucesso!'} 
      end
    else
      respond_to do |format|
        render 'new'
      end
    end
  end

  def update
    
    if @tipo_pagamento.update(tipo_pagamento_params)
      respond_to do |format|
        format.html {redirect_to tipo_pagamentos_path, notice: 'Tipo de pagamento editado com sucesso!'} 
      end
    else
      respond_to do |format|
        render 'edit'
      end
    end
    
  end

  def destroy
    @tipo_pagamento.destroy
    respond_with(@tipo_pagamento)
  end

  private
    def set_listagem 
      @tipo_pagamentos = initialize_grid(TipoPagamento.order(created_at: :desc), per_page: 20)
    end
  
    def set_tipo_pagamento
      @tipo_pagamento = TipoPagamento.find(params[:id])
    end

    def tipo_pagamento_params
      params.require(:tipo_pagamento).permit(:nome, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/despachante_helper.rb
module DespachanteHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/redespacho_helper.rb
module RedespachoHelper
end

app/helpers/tipo_pagamentos_helper.rb
module TipoPagamentosHelper
end

app/views/dashboard/index.html.erb
<h1>Bem vindo ao sistema</h1>

app/views/empresas/_form.html.erb
<%= form_for(@empresa, :html => { :role => "form", :class =>"form-horizontal"}) do |f| %>
  <% if @empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% @empresa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
	<div class="form-wrapper-group">
		<div class="form-group">
			<%= f.label :nome, 'Nome', :class => "col-sm-1 control-label"%>
			<div class="col-sm-3">
			<%= f.text_field :nome, :class =>"form-control" %>
			</div>	
			
			<%= f.label :razao_social, 'Razão Social', :class => "col-sm-2 control-label"%>
			<div class="col-sm-4">
			<%= f.text_field :razao_social, :class =>"form-control" %>
			</div>			
	  	</div>
	</div>
	<div class="form-wrapper-group">
		<div class="form-group">
			<%= f.label :cnpj, 'CNPJ', :class => "col-sm-1 control-label"%>
			<div class="col-sm-3">
			<%= f.text_field :cnpj, :class =>"form-control" %>
			</div>	
			
			<%= f.label :email, 'Email', :class => "col-sm-2 control-label"%>
			<div class="col-sm-4">
			<%= f.email_field :email, :class =>"form-control" %>
			</div>			
	  	</div>
	</div>
	<div class="form-wrapper-group">
		<div class="form-group">
			<%= f.label :telefone, 'Telefone', :class => "col-sm-1 control-label"%>
			<div class="col-sm-3">
			<%= f.text_field :telefone, :class =>"form-control" %>
			</div>	
			
			<%= f.label :responsavel, 'Responsavel', :class => "col-sm-2 control-label"%>
			<div class="col-sm-4">
			<%= f.email_field :responsavel, :class =>"form-control" %>
			</div>			
	  	</div>
	</div>
	<div class="form-wrapper-group">
		<div class="form-group">
			<%= f.label :estado, 'Estado', :class => "col-sm-1 control-label"%>
			<div class="col-sm-3">
			<%= f.text_field :estado, :class =>"form-control" %>
			</div>	
			
			<%= f.label :cidade, 'Cidade', :class => "col-sm-2 control-label"%>
			<div class="col-sm-4">
			<%= f.email_field :cidade, :class =>"form-control" %>
			</div>			
	  	</div>
	</div>
	<div class="form-wrapper-group">
		<div class="form-group">
			<%= f.label :observacao, 'Observação', :class => "col-sm-1 control-label"%>
			<div class="col-sm-3">
			<%= f.text_area :observacao, :class =>"form-control" %>
			</div>		
	  	</div>
	</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/empresas/_registros.html.erb
<h1>Tipos de Pagamento Cadastrados</h1>

<div class="row">
	<div class="table-responsive col-md-12">
		<%= grid(@empresas) do |g|
			
			g.blank_slate  do
		    	content_tag :div, "Nenhum registro encontrado", class: 'well'
		  	end
			
			g.column name: 'Ações' do |option|
				buffer =  link_to('Editar', edit_empresa_path(option)) + ' | '
				buffer += link_to('Excluir', empresa_path(option), method: :delete, data: {confirm: 'Você tem certeza?'})
				raw buffer
			end
			
			g.column name: 'Nome', attribute: 'nome'
			g.column name: 'Razao_social', attribute: 'razao_social'
			g.column name: 'Email', attribute: 'email'
			g.column name: 'Telefone', attribute: 'telefone'
			g.column name: 'Responsavel', attribute: 'responsavel'
			g.column name: 'Cidade', attribute: 'cidade'
			
	    end %>
	</div>

</div>

app/views/empresas/edit.html.erb
<h1>Editing Empresa</h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<%= link_to 'Nova empresa', new_empresa_path, :class => 'btn btn-success' %>

<br/>

<%= render 'registros' %>

app/views/empresas/new.html.erb
<h1>Nova Empresa</h1>
<Br/></Br/>
<%= render 'form' %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @empresa.nome %>
</p>

<p>
  <strong>Razao social:</strong>
  <%= @empresa.razao_social %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @empresa.cnpj %>
</p>

<p>
  <strong>Email:</strong>
  <%= @empresa.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @empresa.telefone %>
</p>

<p>
  <strong>Responsavel:</strong>
  <%= @empresa.responsavel %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @empresa.cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @empresa.estado %>
</p>

<p>
  <strong>Observacoa:</strong>
  <%= @empresa.observacao %>
</p>

<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Controle de cargas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
  
</head>
<body>
	<header>
		<div class="esquerda">
		<p class="titulo">Nome do sistema</p>
		</div>
		<div class="direita">
			<ul id="menu_header">
				<div>
					<li><%= link_to 'Meus dados', edit_user_registration_path %></li>
				</div>
			</ul>
			<%= link_to 'Sair', destroy_user_session_path, :method => :delete %>
		</div>
	</header>
	<div id="painel_esquerdo">
		<div class="info_user">
			<% if !current_user.nil? %>
			<span class="img_avatar">
				<%= image_tag 'fundo_branco.png' %>
			</span>
			<span class="user_name">
				<%=  current_user.email  %>
			</span>
			<span class="user_perfil">
				<%= %>
			</span>
			<span class="ultima_visita">
				Ultima visita: <%= current_user.last_sign_in_at %>
			</span>
			<% end %>
		</div>
		<div class="menu">
			<ul>
				<li><%= link_to 'Redespacho', redespachos_path %></li>
				<li><%= link_to 'Empresas', empresas_path %></li>
			</ul>
		</div>
	</div>
	<div id="painel_conteudo">
		<br/>
		
		<% if !flash.empty? %>
			<%if flash[:error] -%>
				<div class="panel panel-info">
		    <% end -%>
		    <%if flash[:notice] -%>
				<div class="panel panel-info">
		    <% end -%>
		      <div class="panel-heading">
		        <h3 class="panel-title">Atenção</h3>
		      </div>
		      <div class="panel-body">
		        <% flash.each do |name, msg| -%>
			      <%= content_tag :div, msg%>
			    <% end %>
		      </div>
		    </div>
		<% end %>
		
	    
		<%= yield %>
	</div>

</body>
</html>

app/views/layouts/log_in.html.erb
<!DOCTYPE html>
<html style="background-color: #fa7900">
<head>
  <title>Controle de cargas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="login" style="background-color: #fa7900">
		<%= yield %>
	</div>
</body>
</html>

app/views/redespachos/_form.html.erb
<div class="">
	<h2>Redespacho</h2>
	<%= form_for(@redespacho, :html => { :role => "form", :class =>"form-horizontal div_2048"}) do |r| %>
		
		<div class="form-wrapper-group">
			<p>Rementente</p>
			<div class="form-group">
				<%= r.label :remetente, 'Remetente', :class => "col-sm-1 control-label"%>
				<div class="col-sm-2">
				<%= r.text_field :remetente, :class =>"form-control" %>
				</div>
				
				<%= r.label :remetente_cidade, 'Cidade do remetente', :class => "col-sm-1 control-label"%>
				<div class="col-sm-2">
				<%= r.text_field :remetente_cidade, :class =>"form-control" %>
				</div>
		  	</div>
		  	<div class="form-group">
				<%= r.label :empresa_id, 'Empresa', :class => "col-sm-1 control-label"%>
				<div class="col-sm-3">
				<%= r.collection_select :empresa_id ,Empresa.all, :id,:nome,{:include_blank => 'Selecione...'}, {:class => 'form-control'} %>
				</div>
				
		  	</div>
	  	</div>
	  	<div class="form-wrapper-group">
			<p>Destinatario</p>
		  	<div class="form-group">
				<%= r.label :destinatario, 'Destinatario', :class => "col-sm-1 control-label"%>
				<div class="col-sm-2">
				<%= r.text_field :destinatario, :class =>"form-control" %>
				</div>
				
				<%= r.label :destinatario_cidade, 'Cidade', :class => "col-sm-1 control-label"%>
				<div class="col-sm-2">
				<%= r.text_field :destinatario_cidade, :class =>"form-control" %>
				</div>
				
		  	</div>
		</div>
		
		<div class="form-wrapper-group">
			<p>Valores redespacho</p>
		  	<div class="form-group">
		  		
		  		<%= r.label :valor_frete, 'Valor frete', :class => "col-sm-1 control-label "%>
				<div class="col-sm-2">
					<div class="input-group">
						<span class="input-group-addon">R$</span>
						<%= r.text_field :valor_frete, :class =>"form-control currency" %>
					</div>
				</div>
		  		
				<%= r.label :valor_redespacho, 'Valor redespacho', :class => "col-sm-1 control-label "%>
				<div class="col-sm-2">
					<div class="input-group">
						<span class="input-group-addon">R$</span>
						<%= r.text_field :valor_redespacho, :class =>"form-control currency" %>
					</div>
				</div>
		  	</div>
		  	
		  	<div class="form-group">
		  		
		  		<%= r.label :forma_pagamento, 'Forma de pagamento', :class => "col-sm-1 control-label "%>
				<div class="col-sm-2">
					<div class="input-group">
						<%= r.select :forma_pagamento, options_for_select([['Boleto'],['Dinheiro'],['A Vista'],['A Prazo'],['Depósito'],['Cartão de crédito'],['Cheque']]), {}, :class =>"form-control " %>
					</div>
				</div>
		  	</div>
		  	
		  	
		</div>
		
		<div class="form-wrapper-group">
			<p>Outras informações</p>
		  	<div class="form-group">
				<%= r.label :volume, 'Volume', :class => "col-sm-1 control-label"%>
				<div class="col-sm-2">
					<div class="input-group">
						<%= r.text_field :volume, :class =>"form-control" %>
						<span class="input-group-addon">Un.</span>
					</div>
				</div>
				<%= r.label :peso, 'Peso', :class => "col-sm-1 control-label"%>
				<div class="col-sm-2">
					<div class="input-group">
						<%= r.text_field :peso, :class =>"form-control currency" %>
						<span class="input-group-addon">Kg.</span>
					</div>
				</div>
			</div>
			<div class="form-group">
				<%= r.label :nf_valor, 'Valor da NF', :class => "col-sm-1 control-label"%>
				<div class="col-sm-2">
					<div class="input-group">
						<span class="input-group-addon">R$</span>
						<%= r.text_field :nf_valor, :class =>"form-control currency" %>
					</div>
				</div>
				<%= r.label :nf_numero, 'Numero da NF', :class => "col-sm-1 control-label"%>
				<div class="col-sm-2">
					<div class="">
						<%= r.text_field :nf_numero, :class =>"form-control" %>
					</div>
				</div>
			</div>
			<div class="form-group">
				<%= r.label :jadlog_lista_numero, 'JadLog Número da lista', :class => "col-sm-1 control-label"%>
				<div class="col-sm-2">
					<div>
						
						<%= r.text_field :jadlog_lista_numero, :class =>"form-control" %>
					</div>
				</div>
				<%= r.label :jadlog_conhecimento_numero, 'JadLog Número de conhecimento', :class => "col-sm-1 control-label"%>
				<div class="col-sm-2">
					<div class="">
						<%= r.text_field :jadlog_conhecimento_numero, :class =>"form-control" %>
					</div>
				</div>
			</div>
		</div>
		
		
		<div class="form-wrapper-group">
			<p>Datas</p>
		  	<div class="form-group">
				<%= r.label :data_envio, 'Data de envio', :class => "col-sm-1 control-label"%>
				<div class="col-sm-2">
					<%= r.date_field :data_envio, :class =>"form-control" %>
				</div>
			</div>
			<div class="form-group">
				<%= r.label :data_entrega, 'Data de entrega', :class => "col-sm-1 control-label"%>
				<div class="col-sm-2">
					<%= r.date_field :data_entrega, :class =>"form-control" %>
				</div>
				<%= r.label :recebido_por, 'Recebido por', :class => "col-sm-1 control-label"%>
				<div class="col-sm-2">
					<%= r.text_field :recebido_por, :class =>"form-control" %>
				</div>
			</div>
		</div>
		
		<%= r.submit 'Salvar', :class => "btn btn-success" %>
		<%= link_to 'Cancelar', redespachos_path,  :class => "btn btn-danger" %>
	<% end %>
</div>

app/views/redespachos/_registros.html.erb
<div class="table-responsive table-bordered overflow-x ">
	<%= grid(@registros, :class => 'table_2600') do |g|
		g.blank_slate  do
	    	content_tag :div, "Nenhum registro encontrado", class: 'well'
	  	end
	  	
		g.column name: 'Ações' do |option|
			buffer =  link_to('Editar', edit_redespacho_path(option)) + ' | '
			buffer += link_to('Excluir', redespacho_path(option), method: :delete, data: {confirm: 'Você tem certeza?'})
			raw buffer
		end
		
		g.column name: 'Código', attribute: 'id'
		g.column name: 'Empresa', attribute: 'empresa_id', custom_filter: [:empresa, :to_option] do |registro|
			registro.empresa.nome if !registro.empresa.nil?
		end
		g.column name: 'Remetente', attribute: 'remetente'
		g.column name: 'Destinatario', attribute: 'destinatario'
		g.column name: 'Destinatario Cidade', attribute: 'destinatario_cidade'
		g.column name: 'Valor do frete', attribute: 'valor_frete' do |registro| 
		 'R$' + registro.valor_frete.to_s
		end
		g.column name: 'Valor Redespacho', attribute: 'valor_redespacho'do |registro| 
		 'R$' + registro.valor_redespacho.to_s
		end
		g.column name: 'Valor Comissão', attribute: 'valor_comissao'do |registro| 
		 'R$' + registro.valor_comissao.to_s
		end	
		g.column name: 'Forma de pagamento', attribute: 'forma_pagamento'	
		g.column name: 'Quantidade (Volume)', attribute: 'volume'
		g.column name: 'Peso', attribute: 'peso' do |registro|
			registro.peso.to_s + 'Kg'
		end
		#g.column name: 'Fornecedor', attribute: ''
		g.column name: 'NF Valor', attribute: 'nf_valor' do |registro|
		  'R$' + registro.nf_valor.to_s
		end
		g.column name: 'NF Número', attribute: 'nf_numero'
		g.column name: 'Data de envio', attribute: 'data_envio' do |registro|
			registro.data_envio.strftime('%d/%m/%Y') if !registro.data_envio.nil?
		end
		g.column name: 'Data de entrega', attribute: 'data_entrega' do |registro|
			registro.data_entrega.strftime('%d/%m/%Y') if !registro.data_entrega.nil?
		end
		g.column name: 'Recebido por', attribute: 'recebido_por'
		g.column name: 'Jadlog Numero Lista', attribute: 'jadlog_lista_numero'
		g.column name: 'Jadlog Número de conhecimento', attribute: 'jadlog_conhecimento_numero'
		
    end %>
</div>

app/views/redespachos/destroy.html.erb
<h1>Despachante#destroy</h1>
<p>Find me in app/views/despachante/destroy.html.erb</p>

app/views/redespachos/edit.html.erb
<%= render 'registros' %>

<%= render 'form'%>

app/views/redespachos/index.html.erb
<h1>Redespachos realizados</h1>


<%= render 'registros' %>

<%= link_to 'Novo registro', new_redespacho_path, :class => 'btn btn-success'  %>

<div class="edit_area">
	<%=
	 #render 'form' 
	 
	%>
</div>

app/views/redespachos/new.html.erb
<%= render 'registros' %>

<%= render 'form' %>

app/views/tipo_pagamentos/_form.html.erb
<%= form_for(@tipo_pagamento, :html => { :role => "form", :class =>"form-horizontal"}) do |f| %>
  <% if @tipo_pagamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo_pagamento.errors.count, "error") %> prohibited this tipo_pagamento from being saved:</h2>

      <ul>
      <% @tipo_pagamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  	<div class="form-wrapper-group">
		<div class="form-group">
			<%= f.label :nome, 'Nome', :class => "col-sm-1 control-label"%>
			<div class="col-sm-2">
			<%= f.text_field :nome, :class =>"form-control" %>
			</div>			
	  	</div>
	</div>
	
	<div class="form-wrapper-group">
		<div class="form-group">
			<%= f.label :status, 'Status', :class => "col-sm-1 control-label"%>
			<div class="col-sm-2">
			<%= f.select(:status, options_for_select([['Ativo',1], ['Inativo',0]]),{ }, {:class =>"form-control"})  %>
			</div>			
	  	</div>
	</div>
  <div class="actions">
    <%= f.submit 'Salvar', :class => "btn btn-success" %>
    <%= link_to 'Cancelar', tipo_pagamentos_path,  :class => "btn btn-danger" %>
  </div>
<% end %>

app/views/tipo_pagamentos/_registros.html.erb
<h1>Tipos de Pagamento Cadastrados</h1>

<div class="row">
	<div class="table-responsive col-md-8">
		<%= grid(@tipo_pagamentos) do |g|
			
			g.blank_slate  do
		    	content_tag :div, "Nenhum registro encontrado", class: 'well'
		  	end
			
			g.column name: 'Ações' do |option|
				buffer =  link_to('Editar', edit_tipo_pagamento_path(option)) + ' | '
				buffer += link_to('Excluir', tipo_pagamento_path(option), method: :delete, data: {confirm: 'Você tem certeza?'})
				raw buffer
			end
			
			g.column name: 'Tipo', attribute: 'nome'
			g.column name: 'Status', attribute: 'status' do |task|
			  task.status == 1 ? 'Ativo' : 'Inativo'
			end
	    end %>
	</div>

</div>

app/views/tipo_pagamentos/edit.html.erb
<h1>Editando Tipo Pagamento</h1>

<%= render 'form' %>

app/views/tipo_pagamentos/index.html.erb
<%= link_to 'Novo Tipo de pagamento', new_tipo_pagamento_path, :class => 'btn btn-success' %>

<%= render 'registros' %>

<br>

app/views/tipo_pagamentos/new.html.erb
<%= render 'registros' %>

<h1>Novo Tipo Pagamento</h1>

<%= render 'form' %>

app/views/tipo_pagamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @tipo_pagamento.nome %>
</p>

<p>
  <strong>Status:</strong>
  <%= @tipo_pagamento.status %>
</p>

<%= link_to 'Edit', edit_tipo_pagamento_path(@tipo_pagamento) %> |
<%= link_to 'Back', tipo_pagamentos_path %>